<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\dotnetYang\dotnetYang.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\YangSupport\YangSupport.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="yang/*.yang" />
    </ItemGroup>

</Project>
