<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="SSH.NET" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="YangModels\YangModels.csproj" />
    </ItemGroup>

</Project>
