<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <RootNamespace>Compiler.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\dotnetYang\dotnetYang.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="lin.yang" CopyToOutputDirectory="Always"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="ietf-inet-types@2013-07-15.yang" CopyToOutputDirectory="Always"/>
    </ItemGroup>

</Project>
