name: Benchmarks

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Run benchmarks
        run: cd benchmarks && dotnet run -c Release

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: BenchmarkDotNet
          tool: benchmarkdotnet
          output-file-path: benchmarks/BenchmarkDotNet.Artifacts/results/Benchmarks.ParsingBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          summary-always: true
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: true
